
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxlzodyxxkojkyvkofkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bHpvZHl4eGtvamt5dmtvZmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDc4NzgsImV4cCI6MjA1Nzc4Mzg3OH0.6_ChgQq1ZVoiO3Cgi6YFrcM2TE6Sz_JE7yIcPIqB9vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
